version = 0.1
[default.deploy.parameters]
stack_name = "btc-game-backend"
resolve_s3 = true
s3_prefix = "btc-game-backend"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
